//
//  EmailService.swift
//  macappyessir
//
//  Created by Jay Vora on 2/9/26.
//

import Foundation
import AppKit

class EmailService {
    static let shared = EmailService()

    private init() {}

    // MARK: - Send Estimate

    /// Compose email with estimate PDF attachment
    func sendEstimate(for job: Job, pdfURL: URL) -> Bool {
        let subject = "Estimate for \(job.contractorType.rawValue) Project - \(job.clientName)"
        let body = """
        Hi \(job.clientName.components(separatedBy: " ").first ?? job.clientName),

        Thank you for considering us for your \(job.contractorType.rawValue.lowercased()) project.

        Please find attached our detailed estimate for the work at:
        \(job.address)

        Project Overview:
        \(job.description)

        Estimated Cost: \(job.formattedEstimate)

        This estimate is valid for 30 days. If you have any questions or would like to discuss the project further, please don't hesitate to reach out.

        We look forward to working with you!

        Best regards,
        [Your Company Name]

        ---
        Generated by QuoteHub - Your Quote Command Center
        """

        return composeEmail(
            to: job.clientEmail,
            subject: subject,
            body: body,
            attachment: pdfURL
        )
    }

    // MARK: - Send Invoice

    /// Compose email with invoice PDF attachment
    func sendInvoice(for job: Job, pdfURL: URL) -> Bool {
        let subject = "Invoice for \(job.contractorType.rawValue) Project - \(job.clientName)"

        let balanceText = job.isFullyPaid
            ? "Your account is paid in full. Thank you!"
            : "Balance due: \(job.formattedRemainingBalance)"

        let body = """
        Hi \(job.clientName.components(separatedBy: " ").first ?? job.clientName),

        Thank you for your business! Please find attached the invoice for your recent \(job.contractorType.rawValue.lowercased()) project.

        Project Location:
        \(job.address)

        Project Details:
        \(job.description)

        Total Cost: \(job.actualCost != nil ? job.formattedActual! : job.formattedEstimate)
        Paid to Date: \(job.formattedTotalPaid)
        \(balanceText)

        If you have any questions about this invoice, please contact us.

        Thank you for choosing our services!

        Best regards,
        [Your Company Name]

        ---
        Generated by QuoteHub - Your Quote Command Center
        """

        return composeEmail(
            to: job.clientEmail,
            subject: subject,
            body: body,
            attachment: pdfURL
        )
    }

    // MARK: - Generic Email

    /// Compose a custom email
    func composeCustomEmail(
        to: String,
        subject: String,
        body: String,
        attachment: URL? = nil
    ) -> Bool {
        return composeEmail(
            to: to,
            subject: subject,
            body: body,
            attachment: attachment
        )
    }

    // MARK: - Private Methods

    private func composeEmail(
        to: String,
        subject: String,
        body: String,
        attachment: URL? = nil
    ) -> Bool {
        // Validate email
        guard !to.isEmpty, isValidEmail(to) else {
            print("❌ Invalid email address: \(to)")
            return false
        }

        // Create NSSharingService for Mail
        let sharingService = NSSharingService(named: .composeEmail)

        guard let service = sharingService else {
            print("❌ Mail.app not available")
            return false
        }

        // Set recipients
        service.recipients = [to]
        service.subject = subject

        // Prepare items to share
        var items: [Any] = [body]

        // Add attachment if provided
        if let attachment = attachment {
            items.append(attachment)
        }

        // Check if service can perform
        guard service.canPerform(withItems: items) else {
            print("❌ Cannot compose email with these items")
            return false
        }

        // Perform the service
        service.perform(withItems: items)

        print("✅ Email composed successfully")
        return true
    }

    /// Validate email format
    private func isValidEmail(_ email: String) -> Bool {
        let emailRegex = "[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,64}"
        let emailPredicate = NSPredicate(format: "SELF MATCHES %@", emailRegex)
        return emailPredicate.evaluate(with: email)
    }
}

// MARK: - Email Template Builder

extension EmailService {

    /// Generate follow-up email template
    func generateFollowUpTemplate(for job: Job) -> (subject: String, body: String) {
        let subject = "Following up on your \(job.contractorType.rawValue) project"

        let body = """
        Hi \(job.clientName.components(separatedBy: " ").first ?? job.clientName),

        I wanted to follow up regarding the estimate we provided for your \(job.contractorType.rawValue.lowercased()) project at \(job.address).

        Do you have any questions about the estimate? I'd be happy to discuss the project details or adjust the scope if needed.

        Looking forward to hearing from you!

        Best regards,
        [Your Name]
        """

        return (subject, body)
    }

    /// Generate project update email template
    func generateProjectUpdateTemplate(for job: Job) -> (subject: String, body: String) {
        let subject = "Project Update - \(job.contractorType.rawValue)"

        let progressPercent = Int(job.progress * 100)

        let body = """
        Hi \(job.clientName.components(separatedBy: " ").first ?? job.clientName),

        I wanted to give you an update on your \(job.contractorType.rawValue.lowercased()) project.

        Current Progress: \(progressPercent)%

        \(job.notes.isEmpty ? "[Add project notes here]" : job.notes)

        We're on track to complete the project as scheduled. Please let me know if you have any questions or concerns.

        Best regards,
        [Your Name]
        """

        return (subject, body)
    }

    /// Generate completion notification template
    func generateCompletionTemplate(for job: Job) -> (subject: String, body: String) {
        let subject = "Project Completed - \(job.contractorType.rawValue)"

        let body = """
        Hi \(job.clientName.components(separatedBy: " ").first ?? job.clientName),

        Great news! Your \(job.contractorType.rawValue.lowercased()) project at \(job.address) is now complete.

        It was a pleasure working with you on this project. If you have any questions or concerns, please don't hesitate to reach out.

        We'd greatly appreciate it if you could leave us a review or refer us to friends and family.

        Thank you for your business!

        Best regards,
        [Your Name]

        P.S. We're always here if you need any future work done!
        """

        return (subject, body)
    }
}
